import Head from 'next/head';
import { useEffect } from "react";
import { useDispatch } from "react-redux";

// State
import { fetchAllReviews } from '../redux/reviews/reviews-actions';
import useWindowSize from "../hooks/screenSize";

// Components
import Header from '../components/Header/header';
import SearchSection from '../components/SearchSection/searchSection';
import AdvantagesSection from '../components/AdvantagesSection/advantagesSection';
import ToSellSection from '../components/ToSellSection/toSellSection';
import ToPricesSection from '../components/ToPricesSection/toPricesSection';
import ClientImgSection from '../components/ClientImgSection/clientImgSection';
import ClientReviewSection from '../components/ClientsReviewsSections/clientReviewSections';
import PartnersSection from '../components/PartnersSection/partnersSection';
import Footer from '../components/Footer/footer'

export default function Home() {

  const dispatch = useDispatch();
  const size = useWindowSize()

  useEffect(() => {
    dispatch(fetchAllReviews);
  }, []);

  
  return (
    <div>
      <Head>
        <title>Proun Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main className="d-flex flex-column align-items-center">
        <SearchSection width={size.width} />
        <AdvantagesSection width={size.width} />
        <ToSellSection width={size.width} />
        { size.width > 420 ? <ClientImgSection /> : null}
        <ToPricesSection width={size.width} />
        <ClientReviewSection width={size.width} />
        <PartnersSection width={size.width} />
        <Footer width={size.width} />
      </main>
    </div>
  )
}
